name: API test workflow

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Test python API
    defaults:
      run:
        working-directory: ./app
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-python@v2
      with:
        python-version: '3.10'
    - name: install pytest 
      run: python3 -m pip install pytest
    - name: install pytest-cov
      run: python3 -m pip install pytest-cov
    - name: install fastapi
      run: python3 -m pip install fastapi
    - name: install pymongo
      run: python3 -m pip install pymongo
    - name: Run tests
      run: pytest -v --cov=main --cov-report=term-missing 
    - name: Upload coverage reports to Codecov with GitHub Action
      uses: codecov/codecov-action@v2
